#!/bin/bash
  
psql postgres << EOF
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(10);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(10);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(10);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(10);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(10);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(10);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(10);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(5);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(5);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(5);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(5);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
BEGIN;
INSERT INTO plan SELECT id + 200001,typ,current_date + id * '1 seconds'::interval ,val FROM plan;
SELECT pg_sleep(5);
delete from plan;
COPY plan FROM './plan1.dat' (DELIMITER ',', NULL '');
commit;
analyze;
EOF

