#!/bin/bash

mysql -S $PSANDBOX_MYSQL_DIR/mysqld.sock << EOF 
use test
SET profiling = 1;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
select count(*) from sbtest1 LOCK IN SHARE MODE;
SHOW PROFILES;
select sleep(1);
EOF

