begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;
begin;
select 1 from sbtest1 for update;
SELECT pg_sleep(3);
commit;

