#!/bin/bash
  
psql postgres << EOF
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
VACUUM FULL sbtest1;
EOF

